### ISSUE TITLE
Using any image

### ISSUE THREAD

**Issue by minar09** [tianhaoxie/DragGAN_PTI#3]
Hi, thanks for this. What is the image size you tested with? Can we use any images? I am getting errors with 1024 x 768 resolution.

**Comment by tianhaoxie** [comment]
Hi what errors do you have?

**Comment by minar09** [comment]
Error is coming from the lpips loss calculation: `RuntimeError: The size of tensor a (512) must match the size of tensor b (256) at non-singleton dimension 3`

**Comment by tianhaoxie** [comment]
Can you check if you’re using the latest version?

**Comment by minar09** [comment]
Yes, I just cloned the repo yesterday.

**Comment by tianhaoxie** [comment]
Maybe you can provide the detailed error report, the line it happened and the checkpoint you used. I’ll have a look then.

**Comment by minar09** [comment]
Here's the full traceback with checkpoint **stylegan_human_v2_1024.pkl**: 

`Traceback (most recent call last):
  File "/home/pc1/miniconda3/envs/drag/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/pc1/miniconda3/envs/drag/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/media/pc1/New Volume/Minar/gan_inv_pti/inversion.py", line 316, in <module>
    result = pti.train(image, True)
  File "/media/pc1/New Volume/Minar/gan_inv_pti/inversion.py", line 227, in train
    inversed_result = inverse_image(
  File "/media/pc1/New Volume/Minar/gan_inv_pti/inversion.py", line 133, in inverse_image
    p_loss = percept(img_gen, imgs)
  File "/home/pc1/miniconda3/envs/drag/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/media/pc1/New Volume/Minar/gan_inv_pti/lpips/util.py", line 43, in forward
    return self.model.forward(target, pred)
  File "/media/pc1/New Volume/Minar/gan_inv_pti/lpips/dist_model.py", line 151, in forward
    return self.net.forward(in0, in1, retPerLayer=retPerLayer)
  File "/home/pc1/miniconda3/envs/drag/lib/python3.9/site-packages/torch/nn/parallel/data_parallel.py", line 169, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "/home/pc1/miniconda3/envs/drag/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/media/pc1/New Volume/Minar/gan_inv_pti/lpips/networks_basic.py", line 79, in forward
    diffs[kk] = (feats0[kk]-feats1[kk])**2
RuntimeError: The size of tensor a (512) must match the size of tensor b (256) at non-singleton dimension 3`

**Comment by minar09** [comment]
Ran with the latest code again. Getting the same error: 
`...gan_inv/inversion.py", line 214, in cacl_loss
    mse_loss = F.mse_loss(generated_image, real_image)
  File "/home/pc1/miniconda3/envs/drag/lib/python3.9/site-packages/torch/nn/functional.py", line 3294, in mse_loss
    expanded_input, expanded_target = torch.broadcast_tensors(input, target)
  File "/home/pc1/miniconda3/envs/drag/lib/python3.9/site-packages/torch/functional.py", line 74, in broadcast_tensors
    return _VF.broadcast_tensors(tensors)  # type: ignore[attr-defined]
RuntimeError: The size of tensor a (512) must match the size of tensor b (1024) at non-singleton dimension 3
`

**Comment by tianhaoxie** [comment]
Sorry for the late. The stylegan human has different height and weight, which is different from the others, it made this error. You can try other checkpoints with any input image size, it should work.

**Comment by minar09** [comment]
Got it. Thank you.
